version: '3.8'

services:
  # -------------------------------
  # SERVICE : API GoShop
  # -------------------------------
  goshop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goshop-api
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - LOG_LEVEL=debug
      - SERVICE_NAME=goshop-api
      - APP_VERSION=1.0.0
      - APP_PORT=8080
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PORT=5432
      - DB_PASSWORD=root
      - DB_NAME=goshop_db
      - DB_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BCRYPT_COST=4
      - APP_ENV=development
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: unless-stopped

  # -------------------------------
  # SERVICE : PostgreSQL
  # -------------------------------
  db:
    image: postgres:16-alpine
    container_name: goshop-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: goshop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d goshop_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 90s
    restart: unless-stopped

  # -------------------------------
  # SERVICE : Redis
  # -------------------------------
  redis:
    image: redis:7-alpine
    container_name: goshop-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: on-failure

  # -------------------------------
  # SERVICE : Prometheus
  # -------------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: goshop-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      goshop:
        condition: service_healthy
    restart: unless-stopped

  # -------------------------------
  # SERVICE : Loki (logs)
  # -------------------------------
  loki:
    image: grafana/loki:3.2.1
    container_name: goshop-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  # -------------------------------
  # SERVICE : Grafana
  # -------------------------------
  grafana:
    image: grafana/grafana:11.1.0
    container_name: goshop-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_LOG_LEVEL=info
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    restart: unless-stopped

  # -------------------------------
  # SERVICE : Promtail (collecteur logs)
  # -------------------------------
  promtail:
    image: grafana/promtail:3.2.1
    container_name: goshop-promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    restart: unless-stopped

volumes:
  postgres_:
  grafana_data: